### PR TITLE
Refactor listen_addresses to be set in the sample file, and make the sample file easier to overwrite

### LINKED ISSUE #105: Unable to replace postgresql.conf
Using the dockerfile:

```docker
FROM postgres:9.3

COPY postgresql.conf /var/lib/postgresql/data/postgresql.conf
```
(the content of postgresql.conf doesn't matter - at the moment it is a duplicate of what would be there when the image starts)

I can build the image, but when I run it I get the error:

```
postgres_1      | initdb: directory "/var/lib/postgresql/data" exists but is not empty
postgres_1      | If you want to create a new database system, either remove or empty
postgres_1      | the directory "/var/lib/postgresql/data" or run initdb
postgres_1      | with an argument other than "/var/lib/postgresql/data".
```

Why can't I just replace the config file in this way?

### PR DESCRIPTION
**Pull request by tianon**
Closes #120
Fixes #105
Closes #54

(needs documentation updates too)

### CODE REVIEW

**Comment by tianon** [comment]
This also updates the entrypoint to allow for `docker run postgres --flag --flag --flag`.

**Comment by tianon** [comment]
This makes it possible for folks who want to embed a custom config in a new image (or to modify the existing config) to just replace `/usr/share/postgresql/postgresql.conf.sample` instead of thinking about which version of PostgreSQL they're using (or reference `PG_MAJOR`, which isn't even available at the time of `-v` when starting a container).

**Comment by yosifkit** [comment]
LGTM

**Comment by omidraha** [comment]
@tianon 

Now, can you give me an example on how to replace `postgresql.conf` and `pg_hba.conf` configuration files,

I do something like:

```
docker run \
  -v /somewhere/postgres/data:/var/lib/postgresql/data \
  -v /somewhere/postgres/postgresql.conf:/etc/postgres/postgresql.conf:ro \
  -v /somewhere/postgres/pg_hba.conf:/etc/postgres/pg_hba.conf:ro  postgres:9.4
```
But `postgres` ignores them.

**Comment by tianon** [comment]
@omidraha see https://github.com/docker-library/postgres/issues/134#issuecomment-196541551:

> We have not yet added docs on overriding the config, :disappointed:
> 
> If you are replacing the `.example` with something like  `-v /my/local/postgres.conf:/usr/share/postgresql/postgresql.conf.sample` then you would need to make sure that your conf file has a `listen_addresses='*'`. (where as a previously undocumented feature, you could've mounted to `/usr/share/postgresql/9.5/postgresql.conf.sample` and the startup script would've rewritten your listen address line for you.)

**Comment by thongly** [comment]
Found this thread and the related thread that @bw-matthew started, but with much effort.

@tianon - I feel that this is a *very* common use case. Should we include this in the README or docs?

**Comment by FrankFang** [comment]
@omidraha How did you resolve it?

**Pull request merged**
