### PR TITLE
Update to Debian Stretch (slim)

### PR DESCRIPTION
**Pull request by tianon**

### CODE REVIEW

**Comment by tianon** [comment]
For size comparison, `postgres:10` goes from ~288MB down to ~234MB.

**Comment by nathanhruby** [comment]
Hi,

Was this change announced anyplace?  We depend on python being in the container as we delegate some ansible tasks to the postgres container which broke with the change to -slim since python isn't there. I'd like to be more informed of these kind of changes in advance of my users discovering them.

-n

**Comment by tianon** [comment]
It was announced in the only places any changes to the official images are -- here in this repository, and over in the https://github.com/docker-library/official-images repository (which is where _all_ official image updates funnel through).

As noted on the image description on Docker Hub, you probably want to follow PRs in the `library/postgres` label (https://github.com/docker-library/official-images/pulls?utf8=%E2%9C%93&q=is%3Apr+label%3Alibrary%2Fpostgres) there to monitor changes to the image.

As for your specific use case, I'd recommend installing things you need in the image explicitly in your own derivative image, something like:

```dockerfile
FROM postgres:10
RUN apt-get update && apt-get install -y python && rm -rf /var/lib/apt/lists/*
```

(Which you've probably already done, but including it here for completeness.)

**Comment by nathanhruby** [comment]
Yeah, we're going to make some downstream images, this just bit folks today and was a head scratcher.  We didn't expect the underlying install set / distro to change on an existing label, but that's our expectation issue to handle.  Thanks!

**Pull request merged**
