### PR TITLE
Creation multiple users and databases

### PR DESCRIPTION
**Pull request by xtimon**
Execute for test:
`docker run --name some-postgres -p 5432:5432 -e POSTGRES_USERS="user1:user1pass|user2:user2pass|user3:user3password" -e POSTGRES_DATABASES="database1:user1|database2:user2|database3:user3" -e POSTGRES_CONFIGS="work_mem:15MB|fsync:off|full_page_writes:off" -d xtimon/postgres`

### CODE REVIEW

**Comment by gmile** [comment]
Is there anything could be done to merge this? In case there's a reason this is not going to be merged – what is the official / proper way for adding new users / databases?

**Comment by yosifkit** [comment]
Related issues: https://github.com/docker-library/mysql/issues/213, https://github.com/docker-library/mysql/pull/86, https://github.com/docker-library/mysql/pull/18, https://github.com/docker-library/mariadb/pull/63.

So, the answer is to just put scripts in `/docker-entrypoint-initdb.d/`: 
 - https://github.com/docker-library/mysql/pull/86#issuecomment-188316391
 - https://github.com/docker-library/mysql/pull/18#issuecomment-232431316

**Comment by xtimon** [comment]
The official way for adding new users / databases is the same. I didn't broke it. All the environments `POSTGRES_PASSWORD, POSTGRES_USER, POSTGRES_DB` work as expected.

**Comment by Miesvanderlippe** [comment]
@yosifkit 
The init script doesn't really solve my issue. Databases and usernames can be static but I'd much rather have random passwords which I can pass to my other containers. 

Now I get I'd be able to generate a script before calling docker compose, but having it be more integrated would be nicer. I want to pass some Docker-compose variables to the DB which this PR would enable. 

I also get you're annoyed having to answer similar questions all the time, but this PR is very much different from anything you're linking and solves a different problem. I hope you can look at it from my perspective and re-evaluate the value of this PR.

**Comment by tianon** [comment]
The point @yosifkit is making is that this PR can be implemented entirely as a drop-in script in `/docker-entrypoint-initdb.d`, and as such we'd rather not add additional behavior to an already overly complex initialization script we maintain as a delta over what upstream provides.

**Pull request closed without merging**
