### PR TITLE
Replace gosu by chpst from runit.

### PR DESCRIPTION
**Pull request by wmark**
'chpst' offers more features and results in a smaller Docker image.

### CODE REVIEW

**Comment by Starefossen** [comment]
@wmark how much smaller is the resulting image?

**Comment by yosifkit** [comment]
If space is really a concern, couldn't we just nicely ask @tianon to make a dynamic binary instead of the static one?  Is there a feature from `chpst` we need in the images?

**Comment by wmark** [comment]
I believe the question should be asked the other way – why use *gosu*.

The difference is 3.4 MB, by the way. Without *gosu* we don't need some dependencies and the signature verification step (the package manager already does that).

**Comment by sylus** [comment]
I disagree as gosu is already in and across multiple repositories in the docker library. It is also well documented and I think is the default method recommended in some of the docker documentation. So the question should be what does chpst have that gosu doesn't and are they a good enough reason to change the default.

**Comment by wmark** [comment]
@sylus: Please see my initial comment.

**Comment by sylus** [comment]
I read your initial comment but it says it has more features without stating what they are am I missing something. Size comparisons aren't as important because as @tianon has said consistency is more important then bloat.

Docker Library repos using Gosu (I just looked for a few)

1) https://github.com/docker-library/redis/blob/master/3.0/Dockerfile
2) https://github.com/docker-library/mongo/blob/master/3.2/Dockerfile
3) https://github.com/docker-library/postgres/blob/master/9.5/Dockerfile

Docker Docs on Gosu

https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/ (Gosu is mentioned)

**Comment by tianon** [comment]
nuxeo, cassandra, elasticsearch, ghost, kibana, logstash, mongo, postgres,
rabbitmq, redis, and redmine are all current examples where gosu is in use

**Comment by wmark** [comment]
It's about finding the best tool for the job. :-)

Handy features that gosu lack (for a full list see: http://smarden.org/runit/chpst.8.html )
- using locks, for example to prevent multiple starts
- limiting (memory) sizes for a process 
- setuidgid **and** envuidgid

Furthermore:
- chpst is smaller.
- Longer track record, being part of Linux distributions (such as but not limited to Void Linux, Debian; optionally Gentoo)
- chpst/runit can be installed using ```apt-get``` without any additionaly tools or repetitions of verifying processes.

Neither will be cached if not on its own layer, so the point „it's already there/caching saves space“ doesn't apply.

The aforementioned Dockerfiles share the same authors, so the evaluation in favour of *gosu* is really the same and not an independent one.

Using gosu feels like an instance of NIH.

**Comment by sylus** [comment]
Thanks for the through reply! Definitely appreciate learning something new :)

**Comment by wmark** [comment]
@sylus you're welcome. I honestly don't mean to belittle @tianon works. It's perfectly fine to create a one-trick pony. To avoid bloat.

The way Golang currently creates inflated executables and the additional steps to install it currently don't add up. This currently is even more bloated and shouldn't be a best practice.

**Comment by marceloslacerda** [comment]
I'm sorry if this deviates a bit form the topic but, why are we installing a sudo-like solution on those images in general?

From the examples that sylus posted gosu is not used in any step of the build of the images, except in the installation of gosu it self.

And from the Docker guide that sylus posted:

**If you absolutely need** functionality similar to sudo (e.g., initializing the daemon as root but running it as non-root), you may be able to use “gosu”.

I seems pretty clear that you should only install some sudo-like tool if you are going to use it **in the Dockerfile**. It seems like a waste of time and resources otherwise.

**Comment by fwiesel** [comment]
Hi,

is there a chance for that being merged? (After the required changes to make it work again, of course)

I need the following feature:
* using locks, for example to prevent multiple starts

I have a postgres docker image with a NAS volume for persistence, and have to ensure, that not more than one instance is being run on it. (Which happily happens, as the PID of that instance is 1, too)

Currently, I am locking it with `flock`, and looking into upstreaming it, and this looks more promising to me. If not, I would come back to you with my `flock` based approach.

**Comment by tianon** [comment]
Closing old PR -- for folks looking for a slimmer solution than the large binaries Go creates, see https://github.com/ncopa/su-exec (which we usually use as a `gosu` replacement in Alpine-based images where size is important).

**Pull request closed without merging**
