### PR TITLE
Use "apt-get source --compile" to build for Debian architectures upstream doesn't

### PR DESCRIPTION
**Pull request by tianon**

### CODE REVIEW

**Comment by tianon** [comment]
If only Travis supported more arches like `arm64v8` to help test this in a sane way. :innocent:

**Comment by tianon** [comment]
I guess we could fake out the `case` statement to test building on `amd64` too.

**Comment by tianon** [comment]
LOL the image is slightly smaller when we build the `.deb` files ourselves (~266 MB vs ~260 MB); that's encouraging.  Probably some minor update to some build-dep and/or something minor introduced by `nocheck` / `dh_auto_test`. :man_shrugging:

**Comment by tianon** [comment]
I've personally successfully tested several of these versions on both `s390x` and `arm64v8`.

**Comment by yosifkit** [comment]
> In general, PostgreSQL can be expected to work on these CPU architectures: x86, x86_64, IA64, PowerPC, PowerPC 64, S/390, S/390x, Sparc, Sparc 64, ARM, MIPS, MIPSEL, M68K, and PA-RISC
>
> -/ https://www.postgresql.org/docs/current/static/supported-platforms.html

So, it looks fine to me to add these new arches.

**Pull request merged**
