### PR TITLE
Implement TODO for -Eeuo

### PR DESCRIPTION
**Pull request by clairmont32**
I noticed the TODO comment for switching to `-Eeuo` when reviewing the entrypoint for 13.2. I did the switch after searching for a PR that does this but couldnt find one.

### CODE REVIEW

**Comment by tianon** [comment]
So, to clarify, the reason this is a `TODO` is because we need to carefully test all the workflows we reasonably can and make sure at least all the code in this script doesn't break. :sweat_smile:

(Just adding `-u` is the easy bit :see_no_evil: :heart:)

**Comment by clairmont32** [comment]
I figured it might be a bit easier said than done since it wasn't already completed but wanted to submit it just in case it was missed in this particular file. How do you want me to proceed to help?

**Comment by tianon** [comment]
Sorry -- I think the first step would be to enumerate all the things we want/need to test.  The best place to start with that (IMO) is looking through the script for all the "configurable bits" (environment variables we actually act upon) so we can create a plan for verifying that they all still work appropriately.

Essentially anywhere we call `file_env` or have an `if` with a variable, we should figure out a plan for testing that the relevant code still works with `-u` enabled. :+1:

**Comment by yosifkit** [comment]
If we do add `-u`, that would be likely breaking for more users than we expect for their `initdb.d` scripts:

https://github.com/docker-library/postgres/blob/14f13e4b399ed1848fa24c2c1f5bd40c25732bdd/docker-entrypoint.sh#L162-L163

**Pull request closed without merging**
