### PR TITLE
Upgraded 9.4 to Debian Jessie base image.

### PR DESCRIPTION
**Pull request by ypid**
Related to #59.

I have been testing the image for about a day now and now problem so far.

### CODE REVIEW

**Comment by tianon** [comment]
I'd feel much better about this change if we continued to use the upstream-provided repository for it, especially since they have a `jessie-pgdg` dist (http://apt.postgresql.org/pub/repos/apt/dists/jessie-pgdg/).

**Comment by tianon** [comment]
(not that I doubt the Debian maintainer -- upstream's repo will just be more well-supported by upstream, and more likely to get very timely updates)

**Comment by ypid** [comment]
OK sure, I did not know that, thanks. I might change and test this in a few weeks.

**Comment by ypid** [comment]
So far, all seems good. I will keep you up-to-date.

**Pull request closed without merging**
