### PR TITLE
Add PostgreSQL 13 beta 1.

### LINKED ISSUE #735: PostgreSQL 13 beta
Hello, 13 beta 1 was released - https://www.postgresql.org/about/news/2040/. Is there any plan to provide docker image for that? It would be really useful for initial testing.

### PR DESCRIPTION
**Pull request by simi**
closes #735

### CODE REVIEW

**Comment by simi** [comment]
Anyone able to restart CI? Seems stucked in setup phase.

**Comment by tianon** [comment]
Ahh, the hang is actually a legit bug:

```console
Preparing to unpack .../006-slapd_2.4.47+dfsg-3+deb10u2_amd64.deb ...
debconf: unable to initialize frontend: Dialog
debconf: (TERM is not set, so the dialog frontend is not usable.)
debconf: falling back to frontend: Readline
Configuring slapd
-----------------

Please enter the password for the admin entry in your LDAP directory.
```

(It's waiting for input where none can ever happen.)

This is a case of https://bugs.debian.org/929417, and I'll have (hopefully just) one more commit shortly to handle it. :+1:

Thanks for kicking this off!

**Comment by tianon** [comment]
Finally!  Let's do this. :+1:

**Comment by simi** [comment]
:handshake:

**Pull request merged**
