### PR TITLE
Build with the ICU collation provider

### PR DESCRIPTION
**Pull request by dtrebbien**
This builds PostgreSQL with the ICU collation provider:
https://www.postgresql.org/docs/10/static/collation.html

### CODE REVIEW

**Comment by tianon** [comment]
Can you please provide some more detail about why you believe we should change this?

Reading through https://www.postgresql.org/docs/10/static/collation.html#COLLATION-MANAGING, it seems like `icu` isn't necessary recommended but is simply provided as an optional alternative, so IMO sticking to the default provided by upstream makes more sense.

**Comment by yosifkit** [comment]
Minor :+1: from me since it has been enabled since the first 10 devel release on Debian: https://salsa.debian.org/postgresql/postgresql/blob/654f23890eccbca9389e84b0673d228d971d2d73/debian/changelog#L223

**Comment by dtrebbien** [comment]
Hello Tianon,

This is for compatibility with:

 * The postgresql-10 package distributed with Ubuntu 18.04 'Bionic Beaver' and later:  
https://packages.ubuntu.com/bionic/postgresql-10
 * The postgresql-10 package that will be distributed with Debian 10 'buster' and later:  
https://packages.debian.org/buster/postgresql-10
 * The postgresql-10 packages in the official PostgreSQL APT repository:  
http://apt.postgresql.org/pub/repos/apt/

I have also noticed that Heroku's PostgreSQL servers are configured `--with-icu`.

Alpine Linux' `postgresql` package is not configured `--with-icu`.  However, ICU is not that big of a library, so I think that the improved compatibility would be worth the increased image size.

PostgreSQL's ICU support is really convenient for ensuring consistent collation.

Daniel

**Comment by dtrebbien** [comment]
It looks like ICU support is also enabled in RPMs from the official PostgreSQL RPM repository:  
https://git.postgresql.org/gitweb/?p=pgrpms.git;a=blob;f=rpm/redhat/10/postgresql/master/postgresql-10.spec;hb=HEAD

**Comment by tianon** [comment]
Ah, thanks for clarifying @dtrebbien -- we should indeed enable this then, but we'll need to fix `update.sh` to do so only on PostgreSQL 10+ (since support for ICU appears to not have been added until PostgreSQL 10).  Would you like me to take over from here and get the necessary changes to the templating implemented?

**Comment by dtrebbien** [comment]
Okay.

I have switched on "Allow edits from maintainers." if you need that.  (I'm not sure what this does, to be honest, but it sounds like it could be useful.)

You are correct that ICU support was introduced in PostgreSQL 10: https://www.postgresql.org/docs/10/static/release-10.html#id-1.11.6.9.5.13

**Comment by tianon** [comment]
> I have switched on "Allow edits from maintainers." if you need that. (I'm not sure what this does, to be honest, but it sounds like it could be useful.)

That's perfect, thanks.  Pushed up the minor additional change. :+1:

**Comment by tianon** [comment]
Merging since it was green on the previous commit and the new commit only modifies `update.sh`.

**Pull request merged**
