### PR TITLE
Allow "initdb.d" scripts to be executed instead of sourced

### LINKED ISSUE #450: Latest version of postgres container is broken. The previous one which was released 10 ago is working fine. Is it possible to keep at least 2 latest 10.4 versions?

### PR DESCRIPTION
**Pull request by tianon**
Closes #450

cc @willglynn (is this similar to the workaround you've applied in your own scripts?)

### CODE REVIEW

**Comment by willglynn** [comment]
@tianon Well… given an executable `/docker-entrypoint-initdb.d/restore.sh` containing:

```sh
#!/bin/sh -e
gunzip < /something | pg_restore
```

My expectation was that this would run in its own shell with `set -e`. This wasn't (and isn't) the case. My issue in #450 was caused by to the shared environment changing to include `set +o pipefail`.

My workaround was to move this script to `restore.sh.real` and make `restore.sh` say:

```sh
#!/bin/sh -e
/docker-entrypoint-initdb.d/restore.sh.real
```

This runs my script in a separate shell, as expected, allowing the entrypoint script to change however it wants without affecting my restore script's operation. I'd rather it work that way out of the box, of course.

Compatibility is important, so I don't think the `postgres` images can just stop `.`ing scripts and start trying to execute them instead. Checking the provided shell script with `test -x` might be a suitable compromise: anyone who sets `+x` shouldn't be surprised when their script gets executed, and if that's a problem, they could mark it `-x` to revert back to the dot behavior.

**Comment by tianon** [comment]
Fair point, seems like a sane compromise.  PR updated.

(One caveat is that this will mean any files bind-mounted from Windows will be executed instead of sourced.)

**Comment by yosifkit** [comment]
This seems sane and I am working to update the docs. Do we want to add the same functionality to MariaDB, MySQL, and Percona?  They have had `pipefail` since Jan 2016 (https://github.com/docker-library/mysql/pull/134, https://github.com/docker-library/mariadb/pull/37, https://github.com/docker-library/percona/pull/12).

**Comment by tianon** [comment]
Sure, seems sane.

**Pull request merged**
