### PR TITLE
docker-library/postgres#404 Removed volume definition from all images

### PR DESCRIPTION
**Pull request by jannemann**
Fixing #404 by removing volume definition from all images.

### CODE REVIEW

**Comment by jannemann** [comment]
Hmm, the build ist failing: https://travis-ci.org/docker-library/postgres/jobs/340983753

I guess here is why.
gpg --keyserver ha.pool.sks-keyservers.net --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4
gpg: keybox '/tmp/tmp.iZKYM0wW4z/pubring.kbx' created
gpg: keyserver receive failed: Cannot assign requested address

Maybe a rebuild will be sufficient since it is the only build which failed

**Comment by md5** [comment]
You guys do understand this is a breaking change for everyone who currently expects this image to define a volume, right? If they don't specify a volume manually, their data will be written to the container's CoW filesystem and lost if the container needs to be recreated (not to mention terrible IO performance).

**Comment by jannemann** [comment]
This is indeed a problem. Maybe a change to the doc with the explicit mentioning of the VOLUME statement in the Dockerfile will help some people. The advice would be to live with it or to copy&paste the Dockerfile.

**Comment by ms4720** [comment]
This is also causing me issues on kubernetes, the behavior you use is forbidden in kubernetes for production, https://kubernetes.io/docs/concepts/storage/persistent-volumes/ :  

`HostPath (Single node testing only – local storage is not supported in any way and WILL NOT WORK in a multi-node cluster)` 

the default behavior that I can not override is causing data loss and other issues in test.  

I will work with PGDATA for a workaround, but this is broken for k8s 

from #404

**Comment by ms4720** [comment]
> change for everyone who currently expects this image to define a volume, right? If they don't specify a volume manually, their data will be written to the container's CoW filesystem and lost if the container needs to be recreated (not to mention terrible IO performance).

I am having data loss in Kubernetes specifically because of this behavior.  Maybe make a k8s friendly version? ie postgres:VER-blah-k8s for things that are safe for kubernetes

**Comment by yosifkit** [comment]
Closing old issue; we have no plans to remove the `VOLUME` definition. Running pods in Kubernetes via `cri-containerd` won't use Docker-defined volumes anyway.

**Pull request closed without merging**
