### PR TITLE
Feature/add pl language packs

### PR DESCRIPTION
**Pull request by ivan-kolmychek**
#114

### CODE REVIEW

**Comment by tianon** [comment]
Given that these are trivially installable in a dependent `Dockerfile`, I'm not sure there's a strong justification for including them by default.  What's the image size difference before/after including them?

```dockerfile
FROM postgres:9.5

RUN apt-get update \
	&& apt-get install -y \
		postgresql-plperl-$PG_MAJOR=$PG_VERSION \
		postgresql-plpython-$PG_MAJOR=$PG_VERSION \
		postgresql-pltcl-$PG_MAJOR=$PG_VERSION \
	&& rm -rf /var/lib/apt/lists/*
```

Combine that with automated builds (https://docs.docker.com/docker-hub/builds/) and repository links (https://docs.docker.com/docker-hub/builds/#repository-links) and it's reasonably easy to have an up-to-date image built `FROM` this one with additional packages installed as necessary.

**Comment by ivan-kolmychek** [comment]
@tianon you're probably right, it probably does not make much sense to include them in default images, I just shared what worked for me in hope that it will either 1) be accepted or 2) start a dicsussion about how we can do that better.

I still hope we can get them in official builds. Can we create these as separate dockerfiles as tags for official image with automatic builds? Should I rework this PR with that format in mind and push new changes?

**Comment by ivan-kolmychek** [comment]
I'm closing this PR; it still will be findable through google and issues, and it's kind of obvious that it will not be accepted, which is totally fine. :)

**Comment by mpasternak** [comment]
@ivan-kolmychek , it should be also obvious, that it will break perfectly running images because https://github.com/docker-library/postgres/issues/230#issuecomment-343725888 . But only sometimes.

**Comment by ivan-kolmychek** [comment]
@mpasternak thank you for pointing it out, it was not obvious to me - I have used these versions for around 6+ months around the time I've submitted this PR, haven't encountered problems like what you've pointed out to. Still, good catch. 

Please take a look at what exactly versions are being installed - I used there both `PG_MAJOR` and `PG_VERSION`, so packets should be installed exactly for the version of postgres that was installed in previous steps. Maybe that's why I didn't get any problems that you describe, but I am not sure.

**Comment by mpasternak** [comment]
I will use your suggestion and let you know then, thanks. 

Maybe we should pin the PostgreSQL packages versions' installed in the image so they won't be upgraded by apt, what is your opinion on that?

**Comment by ivan-kolmychek** [comment]
Pinning may be less surprising for people who will be building their own images based on these, but there still may be some minor confustion.

If maintainers will decide to use it, I suggest to make it perfectly clear in readme state that versions are pinned with link to some good guide on pinning (like https://wiki.debian.org/AptPreferences but there may be better ones).

**Pull request closed without merging**
