### PR TITLE
worked on docker file

### PR DESCRIPTION
**Pull request by Trickery710**

### CODE REVIEW

**Comment by yosifkit** [comment]
This doesn't look like an actionable PR.

**Comment by Trickery710** [comment]
a GitHub action made it from https://snyk.io/ 
the main recommendation was to change the base image.

**Comment by yosifkit** [comment]
Background: 
>Tags in the [official-images] library file[s] are only built through an update to that library file or as a result of its base image being updated (ie, an image `FROM debian:buster` would be rebuilt when `debian:buster` is built). 
>
>\-https://github.com/docker-library/official-images/tree/2f086314307c04e1de77f0a515f20671e60d40bb#library-definition-files

Official Images FAQ:

> Though not every CVE is removed from the images, we take CVEs seriously and try to ensure that images contain the most up-to-date packages available within a reasonable time frame
>
> \- https://github.com/docker-library/faq/tree/0ad5fd60288109c875a54a37f6581b2deaa836db#why-does-my-security-scanner-show-that-an-image-has-cves

Since our build system makes heavy use of Docker build cache, just rebuilding the all of the Dockerfiles won't cause any change. So we rely on periodic base image updates.

> We strive to publish updated images at least monthly for Debian. We also rebuild earlier if there is a critical security need. Many Official Images are maintained by the community or their respective upstream projects, like Ubuntu, Alpine, and Oracle Linux, and are subject to their own maintenance schedule.
>
> \- from the same FAQ link

**Comment by Trickery710** [comment]
interesting. 
I appreciate the information. your docker files have been very helpful.
do you want me to keep the chain up? or maybe build a separate branch. 
I plan on setting up more.

**Comment by tianon** [comment]
Whatever this is (I still don't fully understand what the purpose of these
added files are), I don't think they're something we want here.

**Pull request closed without merging**
